### ISSUE TITLE
中間テーブルの作成依頼

### ISSUE THREAD

**Issue by ayakotowatari** [Daisuke-1989/warm_master#10]
先ほどはありがとうございました！
中間テーブルとして、以下の６つが必要になると思います。カラムの名前は、他との兼ね合いで変更していただいて構いません。
前半3つには、大学がイベントを作成する際に値をいれます。
後半3つには、学生のregistrationの際に値をいれます。
e_sbj_maps(id, events_id, subjects_id)
e_r_maps(id, events_id, regions_id)
e_l_maps(id, events_id, levels_id)
s_n_maps(id, students_id, nations_id)
s_l_maps(id, students_id, levels_id)
s_sbj_maps(id, students_id, subjects_id
よろしくお願いします！ （編集済み）

**Comment by Daisuke-1989** [comment]
対応完了したので、クローズいたします。
エラーが発生した場合は別issueを作成してください。
